name = "SkewLinearAlgebra"
uuid = "5c889d49-8c60-4500-9d10-5d3a22e2f4b9"
authors = ["smataigne <simonmataigne@gmail.com> and contributors"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
LinearAlgebra = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[targets]
test = ["Test","Random", "SparseArrays"]
